config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :dogs, only: [:index, :create, :new]
  resources :volunteers, only: [:index, :create, :new] do
    resources :walks, only: [:index, :new]
  end
  resources :walks, only: :create

  get '/home', to: 'static#home'

  get '/dogs/longestinspca', to: 'dogs#longestinspca'
  get '/dogs/rottweiler', to: 'dogs#rottweiler'
  get '/dogs/female', to: 'dogs#female'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/auth/:provider/callback', to: 'sessions#create'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
    has_many :walks
    has_many :volunteers, through: :walks
    scope :longestinaspca, -> { order('time_in') }
    scope :rottweiler, -> { where(breed: 'Rottweiler') }
    scope :female, -> { where(gender: 'Female') }

end

app/models/user.rb
class User < ApplicationRecord
    has_many :volunteers
    validates_presence_of :username, :password
    validates_uniqueness_of :username
    has_secure_password
end

app/models/volunteer.rb
class Volunteer < ApplicationRecord
    belongs_to :user
    has_many :walks
    has_many :dogs, through: :walks
    validates_presence_of :name

    def time_method
        self.walks.sum do |t|
            t.duration
        end
    end

end

app/models/walk.rb
class Walk < ApplicationRecord
    belongs_to :volunteer
    belongs_to :dog
    validates_presence_of :duration, :date
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def current_user
        User.find_by(id: session[:user_id])
    end

    def redirect_if_not_logged_in
          redirect_to login_path unless logged_in?
      end

    def logged_in?
        !!current_user
    end

    def log_in(bork)
        session[:user_id] = bork.id
    end

end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController

    def index
        @dogs = Dog.all
    end

    def new
        @dog = Dog.new
    end

    def create
        @dog = Dog.create(dog_params)
        if @dog.save
            redirect_to dogs_path
        else
            render :new
        end
    end

    def longestinspca
        @dogs = Dog.longestinspca
        render :index
    end

    def rottweiler
        @dogs = Dog.rottweiler
        render :index
    end

    def female
        @dogs = Dog.female
        render :index
    end

    private

    def dog_params
        params.require(:dog).permit(:name, :breed, :gender, :age, :time_in)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        if request.env["omniauth.auth"]
            @user = User.find_by(github_uid: request.env["omniauth.auth"]["uid"])
            if @user.nil?
                @user = User.create(username: request.env["omniauth.auth"]["info"]["nickname"], github_uid: request.env["omniauth.auth"]["uid"], password: "github")
            end
                log_in(@user)
                redirect_to volunteers_path
        else
            @user = User.find_by(username: params[:username])
            if !@user
                @error = "Username invalid. Please try again."
                render :new
            elsif !@user.authenticate(params[:password])
                @error = "Password invalid. Please try again."
                render :new
            else 
                log_in(@user)
                redirect_to volunteers_path
            end
        end
    end

    def destroy
        session.clear
        redirect_to login_path
    end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    def home
        render "home"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            log_in(@user)
            redirect_to new_volunteer_path
        else
            render :new
        end
    end

    private

    def user_params
        params.require(:user).permit(:username, :password, :password_confirmation)
    end

end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
    before_action :redirect_if_not_logged_in
    
    def index
        @volunteers = current_user.volunteers
    end
 
    def new
        @volunteer = Volunteer.new
    end

    def create
        @volunteer = current_user.volunteers.build(volunteer_params)
        if @volunteer.save
            redirect_to new_volunteer_walk_path(@volunteer)
        else
            render :new
        end
    end

    private

    def volunteer_params
        params.require(:volunteer).permit(:name)
    end

end

app/controllers/walks_controller.rb
class WalksController < ApplicationController
    before_action :redirect_if_not_logged_in
    before_action :pull_volunteer, only: [:index, :new]

    def index
        redirect_if_invalid
    end

    def new
        redirect_if_invalid
        @walk = Walk.new
    end

    def create
        @volunteer = Volunteer.find_by(id: params[:walk][:volunteer_id])
        if user_authorized?
            @walk = Walk.new(walk_params)
            if @walk.save
                redirect_to volunteer_walks_path(@walk.volunteer)
            else
                render :new
            end
        else
            redirect_to volunteers_path
        end

    end

    private

    def pull_volunteer
        @volunteer ||= Volunteer.find_by(id: params[:volunteer_id])
    end

    def walk_params
        params.require(:walk).permit(:dog_id, :duration, :date, :volunteer_id)
    end

    def user_authorized?
        @volunteer.user && (@volunteer.user.id == current_user.id)
    end

    def redirect_if_invalid
        if @volunteer.nil? || !user_authorized?
            redirect_to volunteers_path
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dog_helper.rb
module DogHelper
end

app/helpers/volunteers_helper.rb
module VolunteersHelper

    def time_conversion(minutes)
        hrs = 0
        min = 0
        if minutes >= 60
          min = minutes % 60
          hrs = (minutes - min) / 60
          min = format('%02d',min)
        else
          min = minutes
        end
        return "#{hrs} hours:#{min} minutes"
    end

end

app/helpers/walk_helper.rb
module WalkHelper
end

app/views/dogs/index.html.erb
<h2>Dogs</h2>

<%= link_to "All Dogs", dogs_path %>
<%= link_to "Order by Time In ASPCA", dogs_longestinaspca_path %>
<%= link_to "Rottweilers", dogs_rottweiler_path %>
<%= link_to "Female", dogs_female_path %>

<% @dogs.each do |dog| %>
<div style="border: 10px inset grey; width: 20rem; margin: 10px; padding: 2px; background-color: white">
<p><h3><u><%= dog.name %></u></h3></p>
<p><b>Breed/Gender: </b><%= dog.breed %>, <%= dog.gender %></p>
<p><b>Age: </b><%= dog.age %> years</p>
<p><b>Time In ASPCA: </b><%= dog.time_in %> months</p>
</div>
<% end %>

app/views/dogs/new.html.erb
<h2>New Doggo</h2>

<p><%= render partial: '/errors', locals: { record: @dog } %></p>

<%= form_for @dog do |t| %>
    <%= t.label :name %>
    <div><%= t.text_field :name %></div>
    <%= t.label :breed %>
    <div><%= t.text_field :breed %></div>
    <%= t.label :gender %>
    <div><%= t.text_field :gender %></div>
    <%= t.label :age %>
    <div><%= t.number_field :age %></div>
    <%= t.label :time_in %>
    <div><%= t.number_field :time_in %></div>
    <%= t.submit "Create Dog" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<font face="verdana">
<title>Dog App</title>
<head><strong><center>Dog App</center></strong></head>
<p></p>
<div><center>
  <a href="/home">Home</a>|
  <a href="/volunteers">View Volunteers</a>|
  <a href="/dogs">View Dogs</a>|
  <a href="/signup">Sign Up</a>|
  <a href="/login">Log In</a>|
  <a href="/logout">Log Out</a></center>
</div>
<p></p>
<style>
body {
	background-image: url("https://cdn1.vectorstock.com/i/1000x1000/91/00/background-with-dog-paw-print-and-bone-vector-2669100.jpg");
      background-repeat:no-repeat;
      background-size:cover;
} 
</style>

<body>
 
<center><%= yield %></center>
 
</body>
</font>
</html>

app/views/users/new.html.erb
<h2>Create New User</h2>

<p><%= render partial: '/errors', locals: { record: @user } %></p

<div><%= form_for @user, url: signup_path do |t| %>
    <div style="border: 10px inset grey; width: 60rem; margin: 10px; padding: 2px; background-color: white">
    <%= t.label :username %>
    <%= t.text_field :username %>
    <%= t.label :password %>
    <%= t.password_field :password %>
    <%= t.label :confirm_password %>
    <%= t.password_field :password_confirmation %>
    <%= t.submit %></div>
<% end %></div>

app/views/volunteers/index.html.erb
<h2>Volunteer List</h2>

<%= link_to "Create New Volunteer", new_volunteer_path %>

<% @volunteers.each do |volunteer| %>
    <div style="border: 10px inset grey; width: 10rem; margin: 10px; background-color: white">
    <h3><%= link_to volunteer.name, volunteer_walks_path(volunteer) %></h3>
    <p><%= time_conversion(volunteer.time_method)%></p></div>
<% end %>

app/views/volunteers/new.html.erb
<h2>New Volunteer</h2>

<p><%= render partial: '/errors', locals: { record: @volunteer } %></p>

<%= form_for @volunteer do |t| %>
    <div style="border: 10px inset grey; width: 20rem; margin: 10px; padding: 2px; background-color: white">
    <%= t.label :name %>
    <div><%= t.text_field :name %></div>
    <%= t.submit "Create Volunteer" %></div>
<% end %>

app/views/walks/index.html.erb
<h2><%= @volunteer.name %>'s Walks</h2>

<%= link_to "Add New Walk", new_volunteer_walk_path(@volunteer) %>

<% @volunteer.walks.each do |walk| %>
    <div style="border: 10px inset grey; width: 10rem; margin: 10px; background-color: white">
    <h3><%= walk.dog.name %></h3>
    <p><%= walk.duration %> minutes</p>
    <p><%= walk.date %></p></div>
<% end %> 

app/views/walks/new.html.erb
<h2>Add New Walk for Volunteer <%= @volunteer.name %></h2>

<p><%= render partial: '/errors', locals: { record: @walk } %></p>

<%= form_for @walk do |t| %>
    <div style="border: 10px inset grey; width: 20rem; margin: 10px; padding: 2px; background-color: white">
    <%= t.label :dog %>
    <div><%= t.collection_select :dog_id, Dog.all, :id, :name, prompt: true %></div>
    <%= t.label :Duration %> (in minutes)
    <div><%= t.number_field :duration %></div>
    <%= t.label :Date %>
    <div><%= t.date_field :date %></div>
    <%= t.hidden_field :volunteer_id, value: @volunteer.id %>
    <%= t.submit "Create Walk" %></div>
<% end %>